///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String iconsIcChatDefault = 'assets/icons/ic_chat_default.png';
  static const String iconsIcChatSelected = 'assets/icons/ic_chat_selected.png';
  static const String iconsIcClipboardDefault = 'assets/icons/ic_clipboard_default.png';
  static const String iconsIcClipboardSelected = 'assets/icons/ic_clipboard_selected.png';
  static const String iconsIcHomeDeafult = 'assets/icons/ic_home_deafult.png';
  static const String iconsIcHomeSelected = 'assets/icons/ic_home_selected.png';
  static const String iconsIcSearch = 'assets/icons/ic_search.png';
  static const String iconsIcSettingDefault = 'assets/icons/ic_setting_default.png';
  static const String iconsIcSettingSelected = 'assets/icons/ic_setting_selected.png';
  static const String imagesCardbg = 'assets/images/cardbg.jpeg';
  static const String imagesDoctor2 = 'assets/images/doctor2.jpeg';
  static const String imagesDoctor3 = 'assets/images/doctor3.png';
  static const String imagesDoctor4 = 'assets/images/doctor4.png';
  static const String imagesDoctor5 = 'assets/images/doctor5.jpeg';
  static const String imagesDoctor6 = 'assets/images/doctor6.jpeg';
  static const String imagesImageAppointment = 'assets/images/image_appointment.png';
  static const String imagesImageConsultant = 'assets/images/image_consultant.png';
  static const String imagesImageDoctor = 'assets/images/image_doctor.jpg';
  static const String imagesImageHospital = 'assets/images/image_hospital.png';
  static const String imagesImageReceipe = 'assets/images/image_receipe.png';
  static const String imagesImageUser = 'assets/images/image_user.jpeg';

}
